### ISSUE TITLE
Missing fields TaxRatePercent and CountryOfPublication

### ISSUE THREAD

**Issue by dgil-unedbarbastro** [jaerith/ONIX-Data#11]
Hi,
I need to receive those fields which currently are not being parsed:

- `OnixPriceTax.TaxRatePercent`
- `OnixPublishingDetail.CountryOfPublication`

I've already added to my local cloned ONIX-Data repo, if you want, I can create a pull-request so we can contribute to this repo.

Regards,
Daniel

**Comment by jaerith** [comment]
Hi Daniel,

Yes, I would definitely welcome the pull request!

Thanks for any contribution,

Aaron

**Comment by dgil-unedbarbastro** [comment]
Great, probably you will have to give me contributor access, because right now, I'm getting a forbidden 403 error:

```bash
Pushing Added_TaxRatePercent_CountryOfPublication
Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/jaerith/ONIX-Data.git/': The requested URL returned error: 403
Pushing to https://github.com/jaerith/ONIX-Data.git

Failed to push the branch to the remote repository. See the Output window for more details.
```

Btw, I've treated the `TaxRatePercent` field as a `string` although in the documentaion it's defined as a Real. I'm doing the same as you do for the field `PriceAmount`.

![image](https://user-images.githubusercontent.com/78791313/122515550-e4fefb00-d00d-11eb-8ebd-7aa045a96806.png)

Regards,
Daniel

**Comment by szolkowski** [comment]
@dgil-unedbarbastro Maybe you could fork this repository and make pull request from your fork? It is usually better way than giving access directly to "source" repo and GitHub have really nice support for such use case.

**Comment by jaerith** [comment]
Yes, @Stanislaw000 is correct.  Perhaps one day I will add other contributors as authors to the project, but for now, I prefer to go with the route of pull requests.

**Comment by jaerith** [comment]
Thanks for the enhancements, @dgil-unedbarbastro!  Yes, I tend to treat numeric fields as strings, mainly since the XML/JSON libraries will fail deserialization in the face of a bad number, and then the entire record becomes unavailable.  But that's where the helper methods come into play.  For example, on Price, you'll find PriceAmountNum, which does the work of providing a numeric version for you.

However, if something bad does actually happen upon deserialization, you can detect and observe the error by calling IsValid() and GetParsingError() on the Product class, as well as GetInputXml() to identify the problematic record.

**Comment by dgil-unedbarbastro** [comment]
> @dgil-unedbarbastro Maybe you could fork this repository and make pull request from your fork? It is usually better way than giving access directly to "source" repo and GitHub have really nice support for such use case.

Done! Forked and created a new Pull Request

**Comment by jaerith** [comment]
Cool!  I merged the pull, and I add some properties for the short tags, along with a helper method for that numeric field.
