### ISSUE TITLE
serializer and deserializer ?

### ISSUE THREAD

**Issue by mirinio** [jaerith/ONIX-Data#17]
Hi,
Great work.

Is there a way to serialize a given onix file with the parser or do you have any example on how to serialize it?
I was currently using the XmlSerializer with typeof OnixMessage but in most cases the OnixMessage is null and I need to get the list of OnixProducts from the foreach you showed in the readme..

Any suggestions?

**Comment by jaerith** [comment]
Hi @mirinio,

Thanks for the compliment!

Unfortunately, this project doesn't support serialization at this time.  It's especially difficult since the ONIX standard has an absurd cornucopia of options, and the purpose of this repo is to parse and then funnel all those options into an actual standardized form as data structures.  In order to go into reverse (i.e., serialization), the project would need to present the user with all supported ONIX options and then write it out correctly.  Reference tags vs. short tags, alternate tag options to contain the same values, using ONIX character encodings or standard HTML character encodings...all of these would need to be supported and handled properly for serialization.  In fact, there's so much work, I would say that it deserves a whole separate project.

As far as your question involving XmlSerializer, are you using the OnixLegacyParser or the OnixParser?  If you use one of those, you don't need to use the XmlSerializer yourself, since that is handled for you.
