### ISSUE TITLE
ONIX-Data + SQUIDEX CMS

### ISSUE THREAD

**Issue by berserkwarwolf** [jaerith/ONIX-Data#2]
Hi, first of all I want to say that your project is very interesting. I haven't found any other like it, open source, .net, onix. Secondly, I was wondering if you knew about Squidex the .NET Headless CMS. My end goal is to build a system to send, receive, and store Book Metadata.

Could I theoretically use your project for metadata ingestion ? What would be the best-practice way of doing it ?

**Comment by jaerith** [comment]
Yes, this project is a very niche one, especially when you combine all those mentioned elements.  However, it's still very important for the publishing industry, especially when it comes to book metadata.

I'm sorry, I haven't heard of Squidex before, but it's probably because I don't generally use CMS solutions.  In any case, yes, you could use this project to ingest book metadata from publishers (and perhaps vendors).  First, you would need to ensure the delivery of the [ONIX](https://www.editeur.org/) content.  Most publishers still use files, but some are starting to transition to an API.  (However, files are still the preference, by far.)  Then, with the guarantee of ONIX content, you could use the code in the "USAGE EXAMPLE" section of the [README](https://github.com/jaerith/ONIX-Data/blob/master/README.md) file in the project.  Finally, you could use the parsed array of OnixLegacyProduct/OnixProduct instances and then upload them to a table.  However, the current example only shows how to parse an ONIX message of Version 2.1 (i.e., the legacy standard), which is still used by many publishers.  In the future, though, all publishers will transition to Version 3.0, and you would need to use the new [ONIXParser](https://github.com/jaerith/ONIX-Data/blob/master/OnixData/OnixParser.cs) class.  I had meant to create an example of using that one, but I hadn't gotten to it yet.  If that would be of help to you, I could create that sooner rather than later.

Still, though, this project would likely only help stage the data, and the data wouldn't truly be useful without some degree of intervention, for two reasons.  One, even though it is a standard, ONIX metadata can be complicated and could require some degree of interpretation, even depending perhaps on the publisher who sent it.  Two, book vendors sometimes have their own schemas/domains/etc., and they have to translate the data so that it fits into their own databases.  All of this can require a substantial amount of work to finally import the data, especially if you are a vendor.

In any case, thank you for your inquiry.  If you have any other questions or if you would like to see the example for the ONIX 3.0 parser, please let me know.

**Comment by jaerith** [comment]
Since I had a few spare moments, I went ahead and included an example on how to use the ONIX 3.0 parser inside the README file.

**Comment by berserkwarwolf** [comment]
@jaerith Thank you so much! I am very sure this will be of great help in understanding this. One more thing, I was tasked with finding out how we should ingest, store and generate Onix metadata, on a Microsoft SQL database. And I am way over my league here. Before I put up my surrender flag, I wanted to ask of you, if it isn't too much trouble of course, a sample MS SQL database, or a model / scheme, whatever I can give my team so that they can model the database, and start working on the ingestion.

Also, there are so few of us, I think we should definitely explore areas for collaboration.

**Comment by jaerith** [comment]
Coming from other projects, the complexity of book data usually comes as a surprise to newcomers, especially since it's much more qualitative than quantitative when compared to other data sets.

I don't actually have a database schema that maps to ONIX.  However, if I were you, I'd start with the [ONIX 2.1 DTD](https://www.editeur.org/files/ONIX%202.1/ONIX_Books_DTDs_2.1_rev.03.zip) (though DTDs are deprecated) and the [ONIX 3.0 XSD](https://www.editeur.org/93/Release-3.0-Downloads/#Schema%20defs).  Though there are other files with the data domains for certain fields (like .ELT files for the DTD), those aren't critical.  I would just focus on the tables and columns.  Even though I've never used it, I've heard that it's fairly easy to create a database schema from a XSD file with a free trial of XmlSpy.

**Comment by jaerith** [comment]
If you do end up going ahead with this ONIX project and need any additional support from me (i.e., code changes), let me know.  I sometimes have free time, and I could probably make such changes easily.  Good luck!
